import './globals.css'
import type { Metadata } from 'next'
import Modal from "@/components/Modal"

export const metadata: Metadata = {
  title: 'Trello AI Clone',
  description: 'Generated by the PAPAFAM',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-[#FF5F6F8]">
        {children}
        <Modal />
        </body>
    </html>
  )
}
